package com.vega.repos.controller;

import jakarta.servlet.http.HttpServletRequest;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.io.IOException;
import java.nio.file.*;
import java.util.Map;

@RestController
public class DownloadController {

    @Value("${vega.cli.jar-path:#{null}}")
    private String configuredJarPath;

    @Value("${vega.cli.version:1.0.28}")
    private String cliVersion;

    private Path resolveJar() {
        String[] searchDirs = { configuredJarPath, "/app/vega-cli" };
        for (String raw : searchDirs) {
            if (raw == null || raw.isBlank()) continue;
            Path p = Paths.get(raw);
            if (!p.isAbsolute()) p = Paths.get("").toAbsolutePath().resolve(p);
            if (Files.isRegularFile(p)) return p;
            if (Files.isDirectory(p)) {
                try (var stream = Files.find(p, 1,
                        (f, a) -> a.isRegularFile()
                                && f.getFileName().toString().startsWith("vega-vcs-")
                                && f.getFileName().toString().endsWith(".jar")
                                && !f.getFileName().toString().contains("sources")
                                && !f.getFileName().toString().contains("javadoc"))) {
                    Path jar = stream.findFirst().orElse(null);
                    if (jar != null) return jar;
                } catch (IOException ignored) {}
            }
        }
        return null;
    }

    @GetMapping("/api/download/vega")
    public ResponseEntity<Resource> downloadVega() throws IOException {
        Path jar = resolveJar();
        if (jar == null) return ResponseEntity.notFound().build();
        Resource resource = new FileSystemResource(jar);
        return ResponseEntity.ok()
                .contentType(MediaType.APPLICATION_OCTET_STREAM)
                .header(HttpHeaders.CONTENT_DISPOSITION,
                        "attachment; filename=\"vega-" + cliVersion + ".jar\"")
                .contentLength(jar.toFile().length())
                .body(resource);
    }

    @GetMapping("/api/version")
    public ResponseEntity<Map<String, String>> version() {
        return ResponseEntity.ok(Map.of("version", cliVersion));
    }

    /**
     * Serves the one-liner install script.
     * Usage: curl -fsSL https://your-server/install.sh | bash
     */
    @GetMapping(value = "/install.sh", produces = "text/plain; charset=utf-8")
    public ResponseEntity<String> installScript(HttpServletRequest request) {
        String baseUrl = buildBaseUrl(request);
        String script = buildInstallScript(baseUrl, false);
        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION, "inline; filename=\"install.sh\"")
                .contentType(MediaType.parseMediaType("text/plain; charset=utf-8"))
                .body(script);
    }

    /**
     * Serves the update script (same logic, just the header differs).
     * Usage: curl -fsSL https://your-server/update.sh | bash
     */
    @GetMapping(value = "/update.sh", produces = "text/plain; charset=utf-8")
    public ResponseEntity<String> updateScript(HttpServletRequest request) {
        String baseUrl = buildBaseUrl(request);
        String script = buildInstallScript(baseUrl, true);
        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION, "inline; filename=\"update.sh\"")
                .contentType(MediaType.parseMediaType("text/plain; charset=utf-8"))
                .body(script);
    }

    private String buildBaseUrl(HttpServletRequest req) {
        String proto = req.getHeader("X-Forwarded-Proto");
        if (proto == null || proto.isBlank()) proto = req.getScheme();
        String host = req.getHeader("X-Forwarded-Host");
        if (host == null || host.isBlank()) host = req.getHeader("Host");
        if (host == null || host.isBlank()) host = req.getServerName() + ":" + req.getServerPort();
        // strip any port from host if proto is standard (avoid https://domain:443)
        if (("https".equals(proto) && host.endsWith(":443"))
                || ("http".equals(proto) && host.endsWith(":80"))) {
            host = host.substring(0, host.lastIndexOf(':'));
        }
        return proto + "://" + host;
    }

    private String buildInstallScript(String baseUrl, boolean isUpdate) {
        String action = isUpdate ? "update" : "install";
        return "#!/usr/bin/env bash\n"
            + "# VEGA CLI " + action + " script — auto-generated by " + baseUrl + "\n"
            + "# Usage: curl -fsSL " + baseUrl + "/" + action + ".sh | bash\n"
            + "set -e\n\n"

            + "GREEN='\\033[0;32m'\n"
            + "YELLOW='\\033[1;33m'\n"
            + "RED='\\033[0;31m'\n"
            + "NC='\\033[0m'\n\n"

            + "VEGA_VERSION=\"" + cliVersion + "\"\n"
            + "VEGA_SERVER=\"" + baseUrl + "\"\n"
            + "JAR_URL=\"$VEGA_SERVER/api/download/vega\"\n"
            + "VEGA_LIB_DIR=\"$HOME/.local/lib/vega\"\n"
            + "VEGA_BIN_DIR=\"$HOME/.local/bin\"\n"
            + "VEGA_JAR=\"$VEGA_LIB_DIR/vega.jar\"\n"
            + "VEGA_BIN=\"$VEGA_BIN_DIR/vega\"\n\n"

            + "echo \"\"\n"
            + "echo \"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\"\n"
            + "echo \"  VEGA CLI v$VEGA_VERSION — " + (isUpdate ? "Updating" : "Installing") + "\"\n"
            + "echo \"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\"\n"
            + "echo \"\"\n\n"

            // Check Java
            + "if ! command -v java &>/dev/null; then\n"
            + "  echo -e \"${RED}✗ Java not found. Please install Java 17+ first:${NC}\"\n"
            + "  echo \"  Ubuntu/Debian: sudo apt install openjdk-17-jre -y\"\n"
            + "  echo \"  macOS:         brew install openjdk@17\"\n"
            + "  exit 1\n"
            + "fi\n\n"

            + "JAVA_VER=$(java -version 2>&1 | awk -F '\"' '/version/ {print $2}' | cut -d. -f1)\n"
            + "if [ -z \"$JAVA_VER\" ] || [ \"$JAVA_VER\" -lt 17 ] 2>/dev/null; then\n"
            + "  echo -e \"${RED}✗ Java 17+ required (found: $JAVA_VER)${NC}\"\n"
            + "  exit 1\n"
            + "fi\n\n"

            + "echo -e \"${GREEN}✓ Java $JAVA_VER found${NC}\"\n\n"

            // Create dirs
            + "mkdir -p \"$VEGA_LIB_DIR\" \"$VEGA_BIN_DIR\"\n\n"

            // Download JAR
            + "echo \"↓ Downloading VEGA v$VEGA_VERSION...\"\n"
            + "TMP_JAR=\"$(mktemp /tmp/vega-XXXXXX.jar)\"\n"
            + "if ! curl -fsSL --progress-bar \"$JAR_URL\" -o \"$TMP_JAR\"; then\n"
            + "  echo -e \"${RED}✗ Download failed. Is the server reachable?${NC}\"\n"
            + "  rm -f \"$TMP_JAR\"\n"
            + "  exit 1\n"
            + "fi\n"
            + "mv \"$TMP_JAR\" \"$VEGA_JAR\"\n"
            + "echo -e \"${GREEN}✓ Downloaded to $VEGA_JAR${NC}\"\n\n"

            // Write wrapper
            + "cat > \"$VEGA_BIN\" << 'WRAPPER'\n"
            + "#!/usr/bin/env bash\n"
            + "VEGA_ENV=\"$HOME/.vega/env\"\n"
            + "[ -f \"$VEGA_ENV\" ] && { set -a; source \"$VEGA_ENV\"; set +a; }\n"
            + "exec java -jar \"$HOME/.local/lib/vega/vega.jar\" \"$@\"\n"
            + "WRAPPER\n"
            + "chmod +x \"$VEGA_BIN\"\n"
            + "echo -e \"${GREEN}✓ Wrapper created at $VEGA_BIN${NC}\"\n\n"

            // Write ~/.vega/env
            + "mkdir -p \"$HOME/.vega\"\n"
            + "if [ ! -f \"$HOME/.vega/env\" ] || ! grep -q 'VEGA_SERVER' \"$HOME/.vega/env\" 2>/dev/null; then\n"
            + "  echo \"VEGA_SERVER=$VEGA_SERVER\" >> \"$HOME/.vega/env\"\n"
            + "  echo -e \"${GREEN}✓ Server set: $VEGA_SERVER${NC}\"\n"
            + "else\n"
            + "  sed -i \"s|VEGA_SERVER=.*|VEGA_SERVER=$VEGA_SERVER|\" \"$HOME/.vega/env\"\n"
            + "  echo -e \"${GREEN}✓ Server updated: $VEGA_SERVER${NC}\"\n"
            + "fi\n\n"

            // PATH check
            + "if [[ \":$PATH:\" != *\":$VEGA_BIN_DIR:\"* ]]; then\n"
            + "  echo \"\"\n"
            + "  echo -e \"${YELLOW}⚠ Add this to your ~/.bashrc or ~/.zshrc:${NC}\"\n"
            + "  echo \"  export PATH=\\\"\\$HOME/.local/bin:\\$PATH\\\"\"\n"
            + "  echo \"\"\n"
            + "  echo \"  Then run: source ~/.bashrc\"\n"
            + "  echo \"\"\n"
            + "  # Auto-append if interactive shell config exists\n"
            + "  for RC in \"$HOME/.bashrc\" \"$HOME/.zshrc\" \"$HOME/.profile\"; do\n"
            + "    if [ -f \"$RC\" ] && ! grep -q '.local/bin' \"$RC\" 2>/dev/null; then\n"
            + "      echo 'export PATH=\"$HOME/.local/bin:$PATH\"' >> \"$RC\"\n"
            + "      echo -e \"${GREEN}✓ PATH added to $RC${NC}\"\n"
            + "      break\n"
            + "    fi\n"
            + "  done\n"
            + "fi\n\n"

            // Final
            + "echo \"\"\n"
            + "echo \"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\"\n"
            + "echo -e \"${GREEN}✓ VEGA v$VEGA_VERSION " + (isUpdate ? "updated" : "installed") + " successfully!${NC}\"\n"
            + "echo \"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\"\n"
            + "echo \"\"\n"
            + "echo \"Quick start:\"\n"
            + "echo \"  vega --version\"\n"
            + "echo \"  vega login <username> <password>\"\n"
            + "echo \"  vega init && vega add . && vega commit -m \\\"init\\\"\"\n"
            + "echo \"\"\n"
            + "echo \"To update later:  curl -fsSL $VEGA_SERVER/update.sh | bash\"\n"
            + "echo \"Or:               vega update\"\n"
            + "echo \"\"\n";
    }
}
