import { useState, useEffect } from 'react'
import { useAuth } from '../context/AuthContext'
import styles from './MetricsPage.module.css'

const API_BASE = '/api'

function StatCard({ value, label, accent }) {
  return (
    <div className={`${styles.statCard} ${accent ? styles[`accent${accent}`] : ''}`}>
      <span className={styles.statValue}>{value}</span>
      <span className={styles.statLabel}>{label}</span>
    </div>
  )
}

function MetricRow({ label, value, description }) {
  return (
    <div className={styles.metricRow}>
      <div className={styles.metricInfo}>
        <span className={styles.metricLabel}>{label}</span>
        {description && <span className={styles.metricDesc}>{description}</span>}
      </div>
      <span className={styles.metricValue}>{value}</span>
    </div>
  )
}

function ProgressBar({ percent, color }) {
  return (
    <div className={styles.progressBarBg}>
      <div
        className={styles.progressBarFill}
        style={{ width: `${Math.min(100, Math.max(0, percent))}%`, background: color || 'var(--accent)' }}
      />
    </div>
  )
}

export default function MetricsPage() {
  const { getAuthHeader, user } = useAuth()
  const [myMetrics, setMyMetrics] = useState(null)
  const [globalMetrics, setGlobalMetrics] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => {
    const headers = getAuthHeader()
    Promise.all([
      fetch(`${API_BASE}/metrics/me`, { headers }),
      fetch(`${API_BASE}/metrics/global`, { headers }),
    ])
      .then(([r1, r2]) => {
        if (!r1.ok || !r2.ok) throw new Error('Failed to fetch metrics')
        return Promise.all([r1.json(), r2.json()])
      })
      .then(([me, global]) => {
        setMyMetrics(me)
        setGlobalMetrics(global)
      })
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false))
  }, [])

  if (loading) return <div className={styles.loading}>Loading metrics...</div>
  if (error) return <div className={styles.error}>{error}</div>

  const my = myMetrics || {}
  const gl = globalMetrics || {}
  const mc = my.commitMetrics || {}
  const mp = my.prMetrics || {}
  const gc = gl.commitMetrics || {}
  const gp = gl.prMetrics || {}

  const pct = (v) => typeof v === 'number' ? v.toFixed(1) : '0.0'
  const num = (v) => typeof v === 'number' ? v : 0

  return (
    <div className={styles.container}>
      <h1>VEGA Metrics Dashboard</h1>
      <p className={styles.subtitle}>
        Performance analytics for <strong>{user?.username}</strong> and the VEGA platform
      </p>

      {/* ── COMMIT METRICS ── */}
      <section className={styles.section}>
        <div className={styles.sectionHeader}>
          <h2>Commit Metrics</h2>
          <span className={styles.badge}>Repository Data</span>
        </div>
        <p className={styles.sectionDesc}>
          Tracks all commits pushed to your repositories and the adoption of VEGA AI-generated commit messages.
        </p>

        <div className={styles.scopeBlock}>
          <h3>My Commits ({user?.username})</h3>
          <div className={styles.statsRow}>
            <StatCard value={num(mc.totalCommits)} label="Total Commits" accent="Blue" />
            <StatCard value={num(mc.aiGeneratedCount)} label="AI Generated" accent="Green" />
            <StatCard value={num(mc.manualCount)} label="Manual" accent="Gray" />
          </div>
          <div className={styles.metricBlock}>
            <MetricRow
              label="AI Adoption Rate"
              value={`${pct(mc.aiAdoptionRatePercent)}%`}
              description="Percentage of commits using VEGA AI-generated messages"
            />
            <ProgressBar percent={num(mc.aiAdoptionRatePercent)} color="var(--success)" />
          </div>
          {num(mc.totalGenerated) > 0 && (
            <div className={styles.metricBlock}>
              <h4>AI Message Generation Details (CLI Sync)</h4>
              <MetricRow label="Total AI Generated" value={num(mc.totalGenerated)} description="Total messages generated by VEGA AI" />
              <MetricRow label="Accepted (First Try)" value={num(mc.acceptedFirst)} description="User accepted the first suggestion" />
              <MetricRow label="Accepted (After Regenerate)" value={num(mc.acceptedAfterRegenerate)} description="User accepted after requesting regeneration" />
              <MetricRow label="Rejected" value={num(mc.rejected)} description="User wrote their own message instead" />
              <MetricRow label="Accept Rate" value={`${pct(mc.acceptRatePercent)}%`} description="Accepted / (Accepted + Rejected)" />
              <ProgressBar percent={num(mc.acceptRatePercent)} />
              <MetricRow label="First-Try Accept Rate" value={`${pct(mc.firstTryAcceptRatePercent)}%`} description="Accepted first suggestion without regeneration" />
              <MetricRow label="Avg Regenerations" value={num(mc.avgRegenerationsWhenRegenerated).toFixed(1)} description="When user regenerated, how many times on average" />
              <MetricRow label="Avg Time to Accept" value={num(mc.avgTimeToAcceptMs) > 0 ? `${(num(mc.avgTimeToAcceptMs) / 1000).toFixed(1)}s` : '-'} description="Average time from generation to acceptance" />
            </div>
          )}
        </div>

        <div className={styles.scopeBlock}>
          <h3>VEGA Global (All Users)</h3>
          <div className={styles.statsRow}>
            <StatCard value={num(gc.totalCommits)} label="Total Commits" accent="Blue" />
            <StatCard value={num(gc.aiGeneratedCount)} label="AI Generated" accent="Green" />
            <StatCard value={num(gc.manualCount)} label="Manual" accent="Gray" />
          </div>
          <div className={styles.metricBlock}>
            <MetricRow
              label="Global AI Adoption Rate"
              value={`${pct(gc.aiAdoptionRatePercent)}%`}
              description="Percentage of all VEGA commits using AI-generated messages"
            />
            <ProgressBar percent={num(gc.aiAdoptionRatePercent)} color="var(--success)" />
          </div>
        </div>
      </section>

      {/* ── PR REVIEW METRICS ── */}
      <section className={styles.section}>
        <div className={styles.sectionHeader}>
          <h2>PR Review Metrics</h2>
          <span className={styles.badge}>Repository Data</span>
        </div>
        <p className={styles.sectionDesc}>
          Tracks pull request activity, review outcomes, and the impact of VEGA PR Summary & Risk analysis on review efficiency.
        </p>

        <div className={styles.scopeBlock}>
          <h3>My Pull Requests ({user?.username})</h3>
          <div className={styles.statsRow}>
            <StatCard value={num(mp.totalPrs)} label="Total PRs" accent="Blue" />
            <StatCard value={num(mp.openCount)} label="Open" accent="Yellow" />
            <StatCard value={num(mp.reviewingCount)} label="Reviewing" accent="Purple" />
            <StatCard value={num(mp.approvedCount)} label="Approved" accent="Green" />
            <StatCard value={num(mp.rejectedCount)} label="Rejected" accent="Red" />
            <StatCard value={num(mp.mergedCount)} label="Merged" accent="Cyan" />
          </div>
          <div className={styles.metricBlock}>
            <MetricRow
              label="PRs with Risk Analysis"
              value={num(mp.withRiskAnalysisCount)}
              description="Pull requests that have VEGA Risk Level assessment (LOW/MEDIUM/HIGH)"
            />
            <MetricRow
              label="Risk Analysis Coverage"
              value={num(mp.totalPrs) > 0 ? `${((num(mp.withRiskAnalysisCount) / num(mp.totalPrs)) * 100).toFixed(1)}%` : '-'}
              description="Percentage of PRs analyzed by VEGA PR Summary & Risk"
            />
            {num(mp.totalPrs) > 0 && (
              <ProgressBar
                percent={num(mp.totalPrs) > 0 ? (num(mp.withRiskAnalysisCount) / num(mp.totalPrs)) * 100 : 0}
                color="var(--accent)"
              />
            )}
          </div>
          {(num(mp.prsWithFeatureCount) > 0 || num(mp.prsWithoutFeatureCount) > 0) && (
            <div className={styles.metricBlock}>
              <h4>Review Time Analysis</h4>
              <MetricRow label="Reviews with PR Summary" value={num(mp.prsWithFeatureCount)} description="PRs reviewed with VEGA PR Summary & Risk feature enabled" />
              <MetricRow label="Reviews without PR Summary" value={num(mp.prsWithoutFeatureCount)} description="PRs reviewed without the feature" />
              <MetricRow label="Avg Review Time (with feature)" value={num(mp.avgReviewTimeWithFeatureMs) > 0 ? `${(num(mp.avgReviewTimeWithFeatureMs) / 1000).toFixed(1)}s` : '-'} description="Average time to complete review when PR Summary was available" />
              <MetricRow label="Avg Review Time (without feature)" value={num(mp.avgReviewTimeWithoutFeatureMs) > 0 ? `${(num(mp.avgReviewTimeWithoutFeatureMs) / 1000).toFixed(1)}s` : '-'} description="Average time to complete review without PR Summary" />
              <MetricRow label="Review Time Improvement" value={`${pct(mp.reviewTimeImprovementPercent)}%`} description="How much faster reviews are with VEGA PR Summary" />
              {num(mp.reviewTimeImprovementPercent) > 0 && (
                <ProgressBar percent={num(mp.reviewTimeImprovementPercent)} color="var(--success)" />
              )}
            </div>
          )}
        </div>

        <div className={styles.scopeBlock}>
          <h3>VEGA Global (All Users)</h3>
          <div className={styles.statsRow}>
            <StatCard value={num(gp.totalPrs)} label="Total PRs" accent="Blue" />
            <StatCard value={num(gp.openCount)} label="Open" accent="Yellow" />
            <StatCard value={num(gp.reviewingCount)} label="Reviewing" accent="Purple" />
            <StatCard value={num(gp.approvedCount)} label="Approved" accent="Green" />
            <StatCard value={num(gp.rejectedCount)} label="Rejected" accent="Red" />
            <StatCard value={num(gp.mergedCount)} label="Merged" accent="Cyan" />
          </div>
          <div className={styles.metricBlock}>
            <MetricRow
              label="Global Risk Analysis Coverage"
              value={num(gp.totalPrs) > 0 ? `${((num(gp.withRiskAnalysisCount) / num(gp.totalPrs)) * 100).toFixed(1)}%` : '-'}
              description="Percentage of all VEGA PRs with Risk Level analysis"
            />
            {num(gp.totalPrs) > 0 && (
              <ProgressBar
                percent={num(gp.totalPrs) > 0 ? (num(gp.withRiskAnalysisCount) / num(gp.totalPrs)) * 100 : 0}
                color="var(--accent)"
              />
            )}
          </div>
        </div>
      </section>
    </div>
  )
}
